sites:
  - name: "bylo"
    sitemap_urls:
      - "https://bylo.ai/sitemap-secondary-page-0.xml"
    active: true
  - name: "pixelcut"
    sitemap_urls:
      - "https://www.pixelcut.ai/sitemap.xml"
    active: true
  - name: "pixelbin"
    sitemap_urls:
      - "https://www.pixelbin.io/default.sitemap.xml"
    active: true
  - name: "pixnova(page)"
    sitemap_urls:
      - "https://pixnova.ai/page-sitemap.xml"
    active: true
  - name: "pixnova(blog)"
    sitemap_urls:
      - "https://pixnova.ai/post-sitemap.xml"
    active: true
  - name: "insmind"
    sitemap_urls:
      - "https://www.insmind.com/sitemap/en.xml"
    active: true
  - name: "pollo"
    sitemap_urls:
      - "https://pollo.ai/sitemap.xml"
    active: true


feishu:
  webhook_url: "https://open.feishu.cn/open-apis/bot/v2/hook/8484db92-3b49-4273-b20a-4ad613c6c0ed"
  secret: "YOUR_SECRET"

storage:
  retention_days: 7
  data_dir: "./data"
