sites:
  - name: "bylo[0]"
    sitemap_urls:
      - "https://bylo.ai/sitemap-secondary-page-0.xml"
    active: true
  - name: "pixelcut[image&video]"
    sitemap_urls:
      - "https://www.pixelcut.ai/sitemap.xml"
    active: true
  - name: "pixelbin[image]"
    sitemap_urls:
      - "https://www.pixelbin.io/default.sitemap.xml"
    active: true
  - name: "pixnova(page)[image&video]"
    sitemap_urls:
      - "https://pixnova.ai/page-sitemap.xml"
    active: true
  - name: "pixnova(blog)[image&video]"
    sitemap_urls:
      - "https://pixnova.ai/post-sitemap.xml"
    active: true
  - name: "insmind[image&video]"
    sitemap_urls:
      - "https://www.insmind.com/sitemap/en.xml"
    active: true
  - name: "pollo[image&video]"
    sitemap_urls:
      - "https://pollo.ai/sitemap.xml"
    active: true
  - name: "imgtoimg"
    sitemap_urls:
      - "https://imgtoimg-ai.com/sitemap.xml"
    active: true
  - name: "dzine"
    sitemap_urls:
      - "https://www.dzine.ai/sitemap.xml"
    active: true
  - name: "flux-ai[image&video]"
    sitemap_urls:
      - "https://flux-ai.io/sitemap.xml"
    active: true
  - name: "imgtoimg(1)"
    sitemap_urls:
      - "https://imgtoimg.ai/sitemap-0.xml"
    active: true
  - name: "artguru"
    sitemap_urls:
      - "https://www.artguru.ai/sitemap.xml"
    active: true
  - name: "picwish[image]"
    sitemap_urls:
      - "https://picwish.com/sitemap.xml"
    active: true
  - name: "clipfly[image&video]"
    sitemap_urls:
      - "https://www.clipfly.ai/sitemaps/en.xml"
    active: true  
  - name: "createimg[image]"
    sitemap_urls:
      - "https://www.createimg.com/page-sitemap.xml"
      - "https://www.createimg.com/post-sitemap1.xml"
      - "https://www.createimg.com/post-sitemap2.xml"
      - "https://www.createimg.com/post-sitemap3.xml"
      - "https://www.createimg.com/post-sitemap4.xml"
      - "https://www.createimg.com/post-sitemap5.xml"
      - "https://www.createimg.com/post-sitemap6.xml"
      - "https://www.createimg.com/post-sitemap7.xml"
    active: true  
  - name: "media"
    sitemap_urls:
      - "https://www.media.io/sitemap.xml"
    active: true  
  - name: "easemate[image&video]"
    sitemap_urls:
      - "https://www.easemate.ai/sitemap.xml"
    active: true 
  - name: "Replicate(0)"
    sitemap_urls:
      - "https://replicate.com/sitemap-models.xml"
      - "https://replicate.com/content-sitemap-0.xml"
    active: true 
  - name: "Fal(0)"
    sitemap_urls:
      - "https://fal.ai/sitemap-0.xml"
    active: true 
  - name: "openrouter(0)"
    sitemap_urls:
      - "https://openrouter.ai/sitemap.xml"
    active: true   
  - name: "vidau[video]"
    sitemap_urls:
      - "https://www.vidau.ai/page-sitemap.xml"
      - "https://www.vidau.ai/page-sitemap2.xml"
      - "https://www.vidau.ai/post-sitemap3.xml"
    active: true   
  - name: "topview[video]"
    sitemap_urls:
      - "https://www.topview.ai/sitemap/sitemap_blog.xml"
      - "https://www.topview.ai/sitemap/sitemap_make_1.xml"
    active: true  
  - name: "pykaso[image&video]"
    sitemap_urls:
      - "https://www.pykaso.ai/sitemap.xml"
    active: true  
  - name: "sendfame[image&video]"
    sitemap_urls:
      - "https://sendfame.com/sitemap.xml"
    active: true  
  - name: "maxstudio[image&video]"
    sitemap_urls:
      - "https://www.maxstudio.ai/sitemap.xml"
    active: true  
  - name: "vizard[video]"
    sitemap_urls:
      - "https://vizard.ai/sitemap.xml"
    active: true  
  - name: "makeugc[video]"
    sitemap_urls:
      - "https://www.makeugc.ai/sitemap.xml"
    active: true  
    


    

feishu:
  webhook_url: "https://open.feishu.cn/open-apis/bot/v2/hook/8484db92-3b49-4273-b20a-4ad613c6c0ed"
  secret: "YOUR_SECRET"

storage:
  retention_days: 7
  data_dir: "./data"
